/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package simparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int RESULT = 6;
  /** RegularExpression Id. */
  int A = 7;
  /** RegularExpression Id. */
  int NA = 8;
  /** RegularExpression Id. */
  int R = 9;
  /** RegularExpression Id. */
  int M = 10;
  /** RegularExpression Id. */
  int O = 11;
  /** RegularExpression Id. */
  int NULL = 12;
  /** RegularExpression Id. */
  int ID = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"AND\"",
    "<RESULT>",
    "\"A\"",
    "\"N/A\"",
    "\"R\"",
    "\"M\"",
    "\"O\"",
    "\"NULL\"",
    "<ID>",
  };

}
