/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package javacccode;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int THEN = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int NOT = 10;
  /** RegularExpression Id. */
  int RESULT = 11;
  /** RegularExpression Id. */
  int REF = 12;
  /** RegularExpression Id. */
  int A = 13;
  /** RegularExpression Id. */
  int NA = 14;
  /** RegularExpression Id. */
  int R = 15;
  /** RegularExpression Id. */
  int M = 16;
  /** RegularExpression Id. */
  int O = 17;
  /** RegularExpression Id. */
  int O1 = 18;
  /** RegularExpression Id. */
  int O2 = 19;
  /** RegularExpression Id. */
  int O4 = 20;
  /** RegularExpression Id. */
  int VOID = 21;
  /** RegularExpression Id. */
  int ANYKEY = 22;
  /** RegularExpression Id. */
  int P1 = 23;
  /** RegularExpression Id. */
  int P2 = 24;
  /** RegularExpression Id. */
  int P3 = 25;
  /** RegularExpression Id. */
  int NUMBER = 26;
  /** RegularExpression Id. */
  int SOME = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int LETTER = 29;
  /** RegularExpression Id. */
  int SPEC_CHAR = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"AND\"",
    "<OR>",
    "\"NOT\"",
    "<RESULT>",
    "<REF>",
    "\"A\"",
    "\"N/A\"",
    "\"R\"",
    "\"M\"",
    "\"O\"",
    "\"O.1\"",
    "\"O.2\"",
    "\"O.4\"",
    "\"Void\"",
    "<ANYKEY>",
    "<P1>",
    "<P2>",
    "<P3>",
    "<NUMBER>",
    "<SOME>",
    "<DIGIT>",
    "<LETTER>",
    "<SPEC_CHAR>",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
  };

}
